name: wt_map
description: A sample Polymer application
dependencies:
    browser: any
    core_elements: any
    paper_elements: any
    polymer: any
    route_hierarchical: any
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js: 
    {'minify':true}